# --- Build React App ---
FROM node:24.13.0-slim AS builder

# Create working directory
RUN mkdir /app
WORKDIR /app

# Copt the app across
COPY . ./

# Install the modules
RUN pnpm -F client i --frozen-lockfile

# Run the app
# CMD ["pnpm", "-F", "client", "start"]

# docker build -t web-app .
# WINDOWS (See this: https://stackoverflow.com/questions/41485217/mount-current-directory-as-a-volume-in-docker-on-windows-10)
# docker run --name web-app -it --rm -p 3000:3000 --mount source="$(pwd)",target=/app web-app
# Or just
# docker run -e CHOKIDAR_USEPOLLING=true --name web-app -it --rm -p 3000:3000 web-app
