packages:
  - client
  - server

catalog:
  eslint: ^8.57.1
  eslint-plugin-import: ^2.32.0
  prettier: ^2.8.8
  typescript: ^4.9.5

minimumReleaseAge: 10080

onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - es5-ext
  - fsevents
