# --- Build Express API ---
FROM node:17-buster-slim as builder

# Create working directory
RUN mkdir /app
WORKDIR /app

# Copt the app across
COPY . ./

# Install the modules
RUN npm ci

# Default port exposure
EXPOSE 9000

COPY wait-for-it.sh /usr/wait-for-it.sh
RUN chmod +x /usr/wait-for-it.sh

# Run the app
CMD ["/usr/wait-for-it.sh", "--timeout=0", "node-mysql:3306", "--", "npm", "run", "dev"]

# docker build -t web-app .
# WINDOWS (See this: https://stackoverflow.com/questions/41485217/mount-current-directory-as-a-volume-in-docker-on-windows-10)
# docker run --name web-app -it --rm -p 3000:3000 --mount source="$(pwd)",target=/app web-app
# Or just
# docker run -e CHOKIDAR_USEPOLLING=true --name web-app -it --rm -p 3000:3000 web-app
