name: ⚡ Prod | Client | Test & Lint
on: [workflow_dispatch]
jobs:
  web-deploy:
    name: 🧪 Lint & Test 🧹
    runs-on: ubuntu-latest
    steps:
      - name: 📩 Check Out Code
        uses: actions/checkout@v4.1.1

      - name: 🍓 Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.23.0

      - name: 🥷 Use Node.js 24.13.0
        uses: actions/setup-node@v6
        with:
          node-version: '24.13.0'
          cache: 'pnpm'

      - name: 🚧 Install Deps
        run: pnpm i --frozen-lockfile --prefer-offline

      - name: 🧹 Lint Build
        run: pnpm --filter client lint

      - name: 🧪 Test Build
        run: pnpm --filter client test

      - name: 🔨 Build Project
        run: INLINE_RUNTIME_CHUNK=false pnpm --filter client build
